repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
    stages:
    - pre-commit
  - id: ruff-format
    stages:
    - pre-commit
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: .venv/Scripts/python.exe -m mypy
    language: system
    types:
    - python
    require_serial: true
    stages:
    - pre-commit
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
    stages:
    - pre-commit
  - id: check-added-large-files
    args:
    - --maxkb=100000
    stages:
    - pre-commit
  - id: check-merge-conflict
    stages:
    - pre-commit
  - id: debug-statements
    stages:
    - pre-commit
