version: '3.7'

services:
  zero:
    image: dgraph/dgraph:v21.03.0
    volumes:
      - ./dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:v21.03.0
    volumes:
      - ./dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080
    depends_on:
      - zero
