version: '3.8'

services:
  # Only include services not already running on the host to avoid port conflicts.
  # Existing containers detected via `docker ps`:
  #  - redis (6379)
  #  - pgvector (5432)
  #  - dgraph (8080/9080)
  # This compose starts MongoDB only, mapped to 27017.

  mongo:
    image: mongo:7
    container_name: ami-orchestrator-mongo-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: x
      MONGO_INITDB_ROOT_PASSWORD: x
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 10s
      retries: 30
