version: 1
compose:
  files:
    - path: docker-compose.data.yml
      description: Data persistence services (PostgreSQL, Redis, Dgraph, Mongo)
    - path: docker-compose.yml
      description: Core application services
    - path: docker-compose.secrets.yml
      description: OpenBao secrets stack
    - path: docker-compose.services.yml
      description: Additional services (Matrix, SearXNG, Vaultwarden, OpenVPN)
services:
  data-postgres:
    summary: PostgreSQL with pgvector extension for structured storage.
    compose:
      file: docker-compose.data.yml
      service: postgres
    module: base
    tags:
      - security:internal-only
      - data:postgres
  data-redis:
    summary: Redis cache backing local development flows.
    compose:
      file: docker-compose.data.yml
      service: redis
    module: base
    tags:
      - security:internal-only
      - data:redis
  data-dgraph:
    summary: Dgraph graph database used by DataOps experiments.
    compose:
      file: docker-compose.data.yml
      service: dgraph
    module: base
    tags:
      - security:internal-only
      - data:dgraph
  data-mongo:
    summary: MongoDB instance from the data stack compose file.
    compose:
      file: docker-compose.data.yml
      service: mongo
    module: base
    tags:
      - security:internal-only
      - data:mongo
  integration-mongo:
    summary: MongoDB instance for integration tests only.
    compose:
      file: docker-compose.yml
      service: mongo
    module: base
    tags:
      - security:internal-only
      - data:mongo
      - testing:integration
  openbao:
    summary: OpenBao development secrets store.
    compose:
      file: docker-compose.secrets.yml
      service: openbao
    module: base
    tags:
      - security:internal-only
      - secrets:openbao
  matrix-postgres:
    summary: PostgreSQL database dedicated to Matrix Synapse homeserver.
    compose:
      file: docker-compose.services.yml
      service: matrix-postgres
    module: streams
    tags:
      - security:internal-only
      - data:postgres
      - streams:matrix
      - streams:data
  matrix-synapse:
    summary: Matrix Synapse homeserver for real-time messaging and event streaming.
    compose:
      file: docker-compose.services.yml
      service: matrix-synapse
    module: streams
    depends_on:
      - matrix-postgres
    tags:
      - security:internal-only
      - streams:matrix
      - streams:messaging
      - streams:events
  matrix-element:
    summary: Element web client for Matrix messaging.
    compose:
      file: docker-compose.services.yml
      service: matrix-element
    module: streams
    depends_on:
      - matrix-synapse
    tags:
      - security:internal-only
      - streams:matrix
      - streams:ui
  secrets-broker:
    summary: Secrets broker service for credential management.
    execution:
      docker:
        enabled: false
      local:
        enabled: true
        kind: python
        command: uv run --python 3.12 base/scripts/run_secrets_broker.py
        cwd: .
    module: base
    env:
      SECRETS_BROKER_HOST: 0.0.0.0
      SECRETS_BROKER_PORT: '8700'
    health:
      tcp:
        host: 0.0.0.0
        port: 8700
        timeout: 5.0
    restart: on-failure
    tags:
      - security:internal-only
      - secrets:broker
  searxng:
    summary: SearXNG metasearch service for browser tooling.
    compose:
      file: docker-compose.services.yml
      service: searxng
    module: browser
    tags:
      - security:internal-only
      - search:searxng
  ux-cms:
    summary: UX CMS Next.js development server.
    execution:
      docker:
        enabled: false
      local:
        enabled: true
        kind: node
        command: npm run dev
        cwd: ux/cms
    module: ux
    env:
      NODE_ENV: development
    health:
      tcp:
        host: localhost
        port: 3000
        timeout: 10.0
    restart: on-failure
    tags:
      - security:internal-only
      - ux:cms
      - ux:dev
profiles:
  data-stack:
    description: Data persistence services required for orchestrator modules.
    services:
      - data-postgres
      - data-redis
      - data-dgraph
      - data-mongo
  integration-mongo:
    description: MongoDB for integration tests.
    services:
      - integration-mongo
  openbao:
    description: Secrets store for credentials and tokens.
    services:
      - openbao
  matrix:
    description: Matrix real-time messaging stack (Synapse + Element + PostgreSQL).
    services:
      - matrix-postgres
      - matrix-synapse
      - matrix-element
  streams-full:
    description: Streams module infrastructure (Matrix + data backends for streaming).
    services:
      - data-postgres
      - data-redis
      - matrix-postgres
      - matrix-synapse
      - matrix-element
  isms:
    description: ISMS communications stack (alias for matrix profile - for compliance integration).
    services:
      - matrix-postgres
      - matrix-synapse
      - matrix-element
  dev:
    description: Full development environment with CMS and all services.
    services:
      - data-postgres
      - data-redis
      - data-dgraph
      - openbao
      - secrets-broker
      - searxng
      - ux-cms
  default:
    description: Complete development stack for orchestrator services.
    services:
      - data-postgres
      - data-redis
      - data-dgraph
      - data-mongo
      - integration-mongo
      - openbao
