[project]
name = "REPLACE_ME_MODULE_NAME"
version = "0.1.0"
description = "REPLACE with module description"
readme = "README.md"
requires-python = ">=3.12"
authors = [
  { name = "Your Team", email = "team@example.com" }
]
dependencies = [
  # Example: "pydantic>=2.7",
]

[project.optional-dependencies]
dev = [
  # Example: "pytest>=8", "mypy>=1.10", "ruff>=0.5",
]

[project.scripts]
# Define console scripts for local runs
# Example: "run-mcp" = "base.scripts.run_mcp:main"

[tool.uv]
# Optional uv settings (index, cache, etc.)
# index-url = "https://your-internal-index/simple"
# extra-index-url = []

[tool.ruff]
target-version = "py312"

[tool.mypy]
python_version = "3.12"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true

# Usage:
# 1) Copy this file into the module root as pyproject.toml.
# 2) Fill in project metadata, dependencies, and scripts.
# 3) Run `uv sync --dev` to resolve and create uv.lock.
# 4) Use `uv run` for all tasks, e.g., `uv run pytest`.

